name: GitHub-Action Java Demo 
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [18]

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11 for x64
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          architecture: x64

      - name: Run the Maven verify phase
        run: mvn --batch-mode --update-snapshots
             cd src
             
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots

      - name: Run tests
        run: |
          cd src
          python -m pytest addition.py
